---
- name: Create django environment directory
  hosts: your_host
  vars:
    environment: your_environment
  tasks:
    - name: Create django environment directory
      file:
        path: "/prod/django_{{ environment }}"
        state: directory
