---
- name: Create /prod/ folder and set permissions
  hosts: your_server
  become: yes

  tasks:
  - name: Create /prod/ folder
    file:
      path: /prod
      state: directory

  - name: Set ownership and permissions for /prod/
    file:
      path: /prod
      owner: your_user
      group: your_group
      mode: "0775"
